version: '3.7'

services:
  prometheus:
    image: prom/prometheus
#    network_mode: host
#    container_name: prometheus
#    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss
#    network_mode: host
#    container_name: grafana
#    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost




#services:
#  prometheus:
#    image:
#      prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./monitoring/config/prometheus.yml:/etc/prometheus/prometheus.yml